blank_issues_enabled: false
contact_links:
    - name: Idea Request
      url: https://github.com/Kilo-Org/kilocode/discussions/categories/ideas
      about: Share and vote on ideas around the future of Kilo Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=kilocode.Kilo-Code&s s ssr=false#review-details
      about: Enjoying Kilo Code? Leave a review here!
