blank_issues_enabled: false
contact_links:
    - name: Idea Request
      url: https://github.com/KodelyDev/kodely/discussions/categories/ideas
      about: Share and vote on ideas around the future of Kilo Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=kodely.Kodely&s s ssr=false#review-details
      about: Enjoying Kodely? Leave a review here!
